import { IAppConfig, INavigationItem, IUser } from "@/utils/types"
import { parseCookies } from "nookies"
import api from "@/api/axiosInstance"

// Application Metadata
export const MetaData = {
  title: "Petronet App",
  description: "Generated by Petronet App",
}

// Application Configuration
export const AppConfig: IAppConfig = {
  siteName: "",
  logoPath: "/assets/images/Elitia_Logo.svg",
  imagePath: "/assets/images",
}

// Navigation Items
export const UserNavigation: INavigationItem[] = [
  { name: "Profile", href: "/profile" },
  { name: "Settings", href: "/settings" },
  { name: "Logout", href: "/logout" },
]

// Function to get the user's image
export const getUserImage = (user: IUser): string => {
  const storedAvatar = sessionStorage.getItem(`avatar_${user.emailAddress}`)
  return storedAvatar || ""
}

// ✅ Save user details locally
export const saveUserDetails = (user: IUser): void => {
  localStorage.setItem("currentUser", JSON.stringify(user))
  localStorage.setItem("currentUserEmail", user.emailAddress)
  sessionStorage.setItem(`avatar_${user.emailAddress}`, "")
}

// ✅ Clear user details (on logout)
export const clearUserDetails = (): void => {
  localStorage.removeItem("currentUser")
  localStorage.removeItem("currentUserEmail")
}

// ✅ Fetch user details
export const getUserDetails = async (email?: string): Promise<IUser | null> => {
  try {
    const cookies = parseCookies()
    const token = cookies.authToken
    if (!token) {
      console.error("No authentication token found in cookies")
      return null
    }

    // If email not passed, get from localStorage
    const userEmail = email || localStorage.getItem("currentUserEmail")
    if (!userEmail) {
      console.error("No email provided or stored for fetching user details")
      return null
    }

    const response = await api.get(`/user/details`, {
      params: { email: userEmail },
      headers: {
        Authorization: `Bearer ${token}`,
      },
    })

    const user = response.data?.Data || response.data?.user || null

    if (user) {
      saveUserDetails(user) // ✅ cache latest user
    }

    return user
  } catch (error) {
    console.error("Error fetching user details", error)

    // 🛑 fallback: try from local cache
    const cached = localStorage.getItem("currentUser")
    return cached ? JSON.parse(cached) : null
  }
}

// ✅ Update user details
export const updateUserDetails = async (
  updatedUser: IUser,
): Promise<{ success: boolean; message: string }> => {
  try {
    const cookies = parseCookies()
    const token = cookies.authToken
    if (!token) {
      return { success: false, message: "No authentication token found" }
    }

    await api.put(`/user/update`, updatedUser, {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    })

    // Update cached user
    saveUserDetails(updatedUser)

    return { success: true, message: "User details updated successfully!" }
  } catch (error) {
    console.error("Error updating user details", error)
    return { success: false, message: "Failed to update user details." }
  }
}